version: "3"
services:
  react-app:
    image: react-app
    build: ./frontend/
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - cheffy-app

  api-server:
    image: api-server
    build: ./backend/
    stdin_open: true
    ports:
      - "5000:5000"
    networks:
      - cheffy-app
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"

networks:
  cheffy-app:
      driver: bridge
volumes:
  mongo-data:
      driver: local