version: "3"
services:
  frontend-side:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - cheffy-app
    depends_on:
      - backend-side

  backend-side:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - cheffy-app
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

networks:
  cheffy-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
